# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0002_requirement_r_info_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='r_info_submit_department',
            field=models.CharField(choices=[(0, '总裁室'), (1, '综合部'), (2, '财务部'), (3, '创新部'), (4, '网销部'), (5, '产险部'), (6, '寿险部'), (7, '数据部'), (8, '信息部')], default='no department', max_length=5, verbose_name='提出部门'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_info_submit_time',
            field=models.DateTimeField(verbose_name='提交时间'),
        ),
    ]
