# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0003_auto_20170329_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='r_category',
            field=models.CharField(blank=True, choices=[('0', '开发类'), ('1', '运维类'), ('2', '紧急类')], default='', max_length=5, verbose_name='需求类别'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_handle',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='需求流转地'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_info_submit_department',
            field=models.CharField(choices=[(0, '总裁室'), (1, '综合部'), (2, '财务部'), (3, '创新业务部'), (4, '网络销售部'), (5, '产险销售部'), (6, '寿险电销部'), (7, '数据管理部'), (8, '信息技术部')], default='', max_length=5, verbose_name='提出部门'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_info_value',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='价值'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_leader',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='任务负责人'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='需求流程状态'),
        ),
    ]
