# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0005_auto_20170330_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_category',
            field=models.IntegerField(blank=True, choices=[(0, '开发类'), (1, '运维类'), (2, '紧急类')], default=0, verbose_name='需求类别'),
        ),
    ]
