# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0007_auto_20170330_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='r_workload',
            field=models.FloatField(blank=True, default=0, verbose_name='工作量'),
        ),
    ]
