# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0009_auto_20170330_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_category',
            field=models.CharField(blank=True, choices=[('0', '开发类'), ('1', '运维类'), ('2', '紧急类')], default=None, max_length=10, null=True, verbose_name='需求类别'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_handle',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='需求流转地'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_info_value',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='价值'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_leader',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='任务负责人'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='需求流程状态'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_workload',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='工作量'),
        ),
    ]
