# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0016_auto_20170330_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_workload',
            field=models.FloatField(default=0, verbose_name='工作量'),
        ),
    ]
