# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0019_auto_20170330_1150'),
    ]

    operations = [
    ]
