# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0020_auto_20170330_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_workload',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='工作量'),
        ),
    ]
