# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0021_auto_20170330_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='r_category',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_handle',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_leader',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_status',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_value_ok',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_workload',
        ),
    ]
