# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0023_auto_20170331_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='r_category',
            field=models.IntegerField(blank=True, choices=[(0, '开发类'), (1, '运维类'), (2, '紧急类')], default=0, null=True, verbose_name='需求类别'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='r_leader',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='任务负责人'),
        ),
    ]
