# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0024_auto_20170331_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='r_category',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_leader',
        ),
    ]
