# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectTracking', '0026_auto_20170331_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='', max_length=10)),
                ('department', models.IntegerField(choices=[(0, '总裁室'), (1, '综合部'), (2, '财务部'), (3, '创新业务部'), (4, '网络销售部'), (5, '产险销售部'), (6, '寿险电销部'), (7, '数据管理部'), (8, '信息技术部')], default=0, verbose_name='提出部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
