# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0027_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='r_info_submit_department',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='r_info_submit_person',
        ),
    ]
