# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0029_requirement_r_info_submit_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='r_info_submit_employee',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='r_info_name',
            field=models.CharField(max_length=100, verbose_name='需求名称'),
        ),
    ]
