# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0032_auto_20170407_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.IntegerField(choices=[(0, '总裁室'), (1, '综合部'), (2, '财务部'), (3, '创新业务部'), (4, '网络销售部'), (5, '产险销售部'), (6, '寿险电销部'), (7, '数据管理部'), (8, '信息技术部')], default=0, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
