# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0033_auto_20170407_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_info_submit_employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提出用户'),
        ),
    ]
