# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0034_auto_20170408_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='r_info_submit_employee',
            new_name='r_info_submit_user',
        ),
    ]
