# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 16:04
from __future__ import unicode_literals

import ProjectTracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0036_requirement_r_file_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_file_requirement',
            field=models.FileField(null=True, upload_to='uploads/', validators=[ProjectTracking.models.validate_file_extension], verbose_name='需求文档'),
        ),
    ]
