# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0038_auto_20170409_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_info_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='需求名称'),
        ),
    ]
