# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 10:03
from __future__ import unicode_literals

import ProjectTracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0041_auto_20170409_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='r_file_requirement',
            field=models.FileField(upload_to='uploads/', validators=[ProjectTracking.models.validate_file_extension], verbose_name='需求文档'),
        ),
    ]
