# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTracking', '0043_requirement_r_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='r_category',
        ),
    ]
